GSA/CIW

ProcessCIW/Utilities/Utilities.cs
README.md

Bug generate email body

---

ProcessCIW/Process/CIWEMails.cs

Removed hard coded bcc email address

Add bcc ref to CIWEmails

---

ProcessCIW/AppSettings.example

Update AppSettings with cc/bcc

---

ProcessCIW/Models/CIW.cs
ProcessCIW/Process/CIWEMails.cs
ProcessCIW/Utilities/Utilities.cs
ProcessCIW/Validation/ValidateCIW.cs

Bug remove repeated code

---

ProcessCIW/ProcessCIW.csproj

Exclude temp folder

---

ProcessCIW/ProcessCIW.csproj

Change examples to do not copy

---

ProcessCIW.sln

Update to VS2015

---

ProcessCIW/AppSettings.example

Bug missing app settings email child care jg

---

ProcessCIW/Validation/ValidateCIW.cs

Update regex for goc poc email to include gsaig.gov

---

ProcessCIW/Process/CIWEMails.cs

Add logic to not send zonal email cc for t1c

---

ProcessCIW/Properties/AssemblyInfo.cs

Auto remove white space
Update version to 2.0

Update version to 2.0

---

ProcessCIW/Mapping/CIWMapping.cs
ProcessCIW/Process/CIWEMails.cs
ProcessCIW/Process/InsertCIW.cs
ProcessCIW/Program.cs
ProcessCIW/Utilities/Email.cs
ProcessCIW/Utilities/Utilities.cs
ProcessCIW/Validation/ValidateCIW.cs

Auto fix white space, fix comment typos
#76

Update sp audit log changes

---

ProcessCIW/Process/ProcessDocuments.cs

Switch from surrounding inner text with single quotes to delimited double quotes
#80

Fix apostrophe bug

---

ProcessCIW/Validation/ValidateCIW.cs

Change pob city length from 24 to 75

---

ProcessCIW/Process/InsertCIW.cs

Fix doe bug, inserts date if not empty string, else inserts dbnull

Fix DOE bug

---

ProcessCIW/Models/CIW.cs
ProcessCIW/Process/InsertCIW.cs
ProcessCIW/Utilities/Utilities.cs
ProcessCIW/Validation/ValidateCIW.cs

* **Add** trim to model
* **Add** validation for white space
* **Add** code to insert DBNull if not a valid date
* [Release script](https://drive.google.com/open?id=10YPuK5rERz9k3xS33aFm901rJ7JB8V33hJrcwlc37eQ)

Prior Investigation Date Fix

---

ProcessCIW/Mapping/Constants.cs
ProcessCIW/Process/InsertCIW.cs
ProcessCIW/Process/ProcessDocuments.cs
ProcessCIW/Validation/ValidateCIW.cs

* **Added** validation to contract number type so that it is now required when uploading a CIW
* **Added** logic to not insert TODO into database if contract number type is base contract number
* **Added** code to ensure Contract number is always inserted into the database, it is a required field in GCIMS
* **Updated** both stored procedures for inserting contract headers to work with changes to code
* **Added** contract number to both stored procedures
* **Removed** contract name from insert clause in both stored procedures

Contract number fix

---

ProcessCIW/Models/CIW.cs
ProcessCIW/Process/CIWEMails.cs
ProcessCIW/Process/ProcessDocuments.cs
ProcessCIW/Program.cs
ProcessCIW/Validation/ValidateCIW.cs

removed dupes code, they no longer exist

fix for nested tags

---

ProcessCIW/Mapping/CIWMapping.cs
ProcessCIW/Models/CIW.cs
ProcessCIW/Process/ProcessDocuments.cs

Initial testing demonstrated correct insertion of fips codes obtained from database where CIW had incorrect code.

Use fips lookup table to get fips code

---

ProcessCIW/Models/CIW.cs

Trim first middle and last name

---

ProcessCIW/Process/InsertCIW.cs

fix ssn last 4 bug

---

ProcessCIW/Models/CIW.cs
ProcessCIW/Process/InsertCIW.cs
ProcessCIW/Process/ProcessDocuments.cs
ProcessCIW/Utilities/Utilities.cs
ProcessCIW/Validation/ValidateCIW.cs

Dev to test

---

ProcessCIW/Models/CIW.cs
ProcessCIW/ProcessCIW.csproj
ProcessCIW/Utilities/Extension.cs
ProcessCIW/packages.config

Contract number cleanup

---

ProcessCIW/Utilities/Utilities.cs

date not in name bug fix

---

.gitignore
ProcessCIW/Validation/ValidateCIW.cs

update validation when citizen is us

---

ProcessCIW/Process/InsertCIW.cs
ProcessCIW/Process/ProcessDocuments.cs
ProcessCIW/Utilities/Utilities.cs
ProcessCIW/Validation/ValidateCIW.cs
ProcessCIW/packages.config

ciw process updated

---

ProcessCIW/Validation/ValidateCIW.cs

Do Not Allow ".gov" Domains for Personal E-Mail
